<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_pos_segment_payment_model extends CI_Model
{

    public $table = 'ref_pos_segment_payment';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,segment_id,payment_id,created_date,modified_date,created_by,modified_by');
        $this->datatables->from('ref_pos_segment_payment');
        //add this line for join
        //$this->datatables->join('table2', 'ref_pos_segment_payment.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('referensi/ref_pos_segment_payment/update/$1'),'Update')." | ".anchor(base_url('referensi/ref_pos_segment_payment/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('segment_id', $q);
	$this->db->or_like('payment_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('segment_id', $q);
	$this->db->or_like('payment_id', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ref_pos_segment_payment_model.php */
/* Location: ./application/models/Ref_pos_segment_payment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-21 10:35:45 */
/* http://harviacode.com */