<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ref_pos_segment_model extends CI_Model
{

    public $table = 'ref_pos_segment';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,code,name,short_name,description,status,is_cover,is_captain_order,is_phone_number,is_waiter,is_autoincrement_tbl_no,is_guest_profile,is_reservation,is_rate_code,is_service,is_tax,surcharge_percent,min_charge,hourly_charge,is_food_entry,is_beverage_alcohol,is_beverage_non_alcohol,created_date,modified_date,created_by,modified_by');
        $this->datatables->from('ref_pos_segment');
        //add this line for join
        //$this->datatables->join('table2', 'ref_pos_segment.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('referensi/ref_pos_segment/update/$1'),'Update')." | ".anchor(base_url('referensi/ref_pos_segment/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('short_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('is_cover', $q);
	$this->db->or_like('is_captain_order', $q);
	$this->db->or_like('is_phone_number', $q);
	$this->db->or_like('is_waiter', $q);
	$this->db->or_like('is_autoincrement_tbl_no', $q);
	$this->db->or_like('is_guest_profile', $q);
	$this->db->or_like('is_reservation', $q);
	$this->db->or_like('is_rate_code', $q);
	$this->db->or_like('is_service', $q);
	$this->db->or_like('is_tax', $q);
	$this->db->or_like('surcharge_percent', $q);
	$this->db->or_like('min_charge', $q);
	$this->db->or_like('hourly_charge', $q);
	$this->db->or_like('is_food_entry', $q);
	$this->db->or_like('is_beverage_alcohol', $q);
	$this->db->or_like('is_beverage_non_alcohol', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('short_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('is_cover', $q);
	$this->db->or_like('is_captain_order', $q);
	$this->db->or_like('is_phone_number', $q);
	$this->db->or_like('is_waiter', $q);
	$this->db->or_like('is_autoincrement_tbl_no', $q);
	$this->db->or_like('is_guest_profile', $q);
	$this->db->or_like('is_reservation', $q);
	$this->db->or_like('is_rate_code', $q);
	$this->db->or_like('is_service', $q);
	$this->db->or_like('is_tax', $q);
	$this->db->or_like('surcharge_percent', $q);
	$this->db->or_like('min_charge', $q);
	$this->db->or_like('hourly_charge', $q);
	$this->db->or_like('is_food_entry', $q);
	$this->db->or_like('is_beverage_alcohol', $q);
	$this->db->or_like('is_beverage_non_alcohol', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('modified_date', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('modified_by', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        //$this->db->where($this->id, $id);
        //$this->db->delete($this->table);
        
        $this->db->set('status', 2);
        $this->db->where($this->id, $id);
        $this->db->update($this->table);
    }

}

/* End of file Ref_pos_segment_model.php */
/* Location: ./application/models/Ref_pos_segment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 18:40:03 */
/* http://harviacode.com */