<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');

class Pos_store extends CI_Controller {
	function __construct() {
		parent::__construct();
		$this->load->model('Pos_store_model');
		$this->load->library('form_validation');
		$this->load->library('datatables');
		is_logged_in();
	}

	public function index() {
		$data['title'] = "Store";
		datatables('setting/pos_store/pos_store_list', $data);
	}

	public function json() {
		header('Content-Type: application/json');
		echo $this->Pos_store_model->json();
	}


	public function create() {
		$data = array('button' => 'Create', 'title' => 'Store', 'action' => base_url('setting/pos_store/create_action'), 'id' => set_value('id'), 'store_name' => set_value('store_name'), 'email' => set_value('email'), 'phone' => set_value('phone'),);
		form('setting/pos_store/pos_store_form', $data);
	}

	public function create_action() {
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->create();
		} else {
			$data = array('store_name' => $this->input->post('store_name', TRUE), 'email' => $this->input->post('email', TRUE), 'phone' => $this->input->post('phone', TRUE),);

			$this->Pos_store_model->insert($data);
			$this->session->set_flashdata('message', 'Create Record Success');
			redirect(base_url('setting/pos_store'));
		}
	}

	public function update($id) {
		$row = $this->Pos_store_model->get_by_id($id);

		if ($row) {
			$data = array('button' => 'Update', 'title' => 'Store', 'action' => base_url('setting/pos_store/update_action'), 'id' => set_value('id', $row->id), 'store_name' => set_value('store_name', $row->store_name), 'email' => set_value('email', $row->email), 'phone' => set_value('phone', $row->phone),);
			form('setting/pos_store/pos_store_form', $data);
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(base_url('setting/pos_store'));
		}
	}

	public function update_action() {
		$this->_rules();

		if ($this->form_validation->run() == FALSE) {
			$this->update($this->input->post('id', TRUE));
		} else {
			$data = array('store_name' => $this->input->post('store_name', TRUE), 'email' => $this->input->post('email', TRUE), 'phone' => $this->input->post('phone', TRUE),);

			$this->Pos_store_model->update($this->input->post('id', TRUE), $data);
			$this->session->set_flashdata('message', 'Update Record Success');
			redirect(base_url('setting/pos_store'));
		}
	}

	public function delete($id) {
		$row = $this->Pos_store_model->get_by_id($id);

		if ($row) {
			$this->Pos_store_model->delete($id);
			$this->session->set_flashdata('message', 'Delete Record Success');
			redirect(base_url('setting/pos_store'));
		} else {
			$this->session->set_flashdata('message', 'Record Not Found');
			redirect(base_url('setting/pos_store'));
		}
	}

	public function _rules() {
		$this->form_validation->set_rules('store_name', 'store name', 'trim|required');
		$this->form_validation->set_rules('email', 'email', 'trim|required');
		$this->form_validation->set_rules('phone', 'phone', 'trim|required');

		$this->form_validation->set_rules('id', 'id', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
	}

}

/* End of file Pos_store.php */
/* Location: ./application/controllers/Pos_store.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-06 18:48:21 */
/* http://harviacode.com */
